# Generated by Django 3.2 on 2022-05-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualize', '0002_ai_model_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ai_model',
            name='path',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='ai_model',
            name='score',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ai_model',
            name='train_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='ai_model',
            name='train_start',
            field=models.DateTimeField(null=True),
        ),
    ]
