# Generated by Django 3.2 on 2022-05-06 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visualize', '0003_auto_20220504_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deploy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField()),
                ('deploy_start', models.DateTimeField(null=True)),
                ('deploy_end', models.DateTimeField(null=True)),
                ('ai_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='visualize.ai_model')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
